# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: code_search.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'code_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ode_search.proto\x12\x0f\x61gentcodesearch\"\x85\x01\n\rSymbolRequest\x12\x13\n\x0bsymbol_name\x18\x01 \x01(\t\x12\x30\n\x0bsearch_mode\x18\x02 \x01(\x0e\x32\x1b.agentcodesearch.SearchMode\x12\x16\n\x0e\x63ontext_before\x18\x03 \x01(\x05\x12\x15\n\rcontext_after\x18\x04 \x01(\x05\"a\n\nSymbolInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\">\n\x0eSymbolResponse\x12,\n\x07symbols\x18\x01 \x03(\x0b\x32\x1b.agentcodesearch.SymbolInfo\"}\n\x11TextSearchRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontext_before\x18\x02 \x01(\x05\x12\x15\n\rcontext_after\x18\x03 \x01(\x05\x12\x13\n\x0bsearch_path\x18\x04 \x01(\t\x12\x16\n\x0e\x66ile_extension\x18\x05 \x01(\t\"K\n\x10TextSearchResult\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0bline_number\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"H\n\x12TextSearchResponse\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32!.agentcodesearch.TextSearchResult*O\n\nSearchMode\x12\x15\n\x11SYMBOL_ENTIREWORD\x10\x00\x12\x14\n\x10SYMBOL_SUBSTRING\x10\x01\x12\x14\n\x10SYMBOL_PRESTRING\x10\x02\x32\xba\x01\n\x13SymbolSearchService\x12N\n\x0b\x46indSymbols\x12\x1e.agentcodesearch.SymbolRequest\x1a\x1f.agentcodesearch.SymbolResponse\x12S\n\x08\x46indText\x12\".agentcodesearch.TextSearchRequest\x1a#.agentcodesearch.TextSearchResponseB\x1b\xaa\x02\x18\x41gentCodeSearchExtensionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030AgentCodeSearchExtension'
  _globals['_SEARCHMODE']._serialized_start=615
  _globals['_SEARCHMODE']._serialized_end=694
  _globals['_SYMBOLREQUEST']._serialized_start=39
  _globals['_SYMBOLREQUEST']._serialized_end=172
  _globals['_SYMBOLINFO']._serialized_start=174
  _globals['_SYMBOLINFO']._serialized_end=271
  _globals['_SYMBOLRESPONSE']._serialized_start=273
  _globals['_SYMBOLRESPONSE']._serialized_end=335
  _globals['_TEXTSEARCHREQUEST']._serialized_start=337
  _globals['_TEXTSEARCHREQUEST']._serialized_end=462
  _globals['_TEXTSEARCHRESULT']._serialized_start=464
  _globals['_TEXTSEARCHRESULT']._serialized_end=539
  _globals['_TEXTSEARCHRESPONSE']._serialized_start=541
  _globals['_TEXTSEARCHRESPONSE']._serialized_end=613
  _globals['_SYMBOLSEARCHSERVICE']._serialized_start=697
  _globals['_SYMBOLSEARCHSERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
